name: MacOS SSH to GitHub Actions

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:

jobs:
  ssh:
    runs-on: macos-11.0

    env:
      # Change These If You Are Forking The Repo
      GitHubMail: "jainsamyak2002.sj@gmail.com"
      GitHubName: "Samyak"

    steps:
     - name: Android Emulator Runner
       uses: ReactiveCircus/android-emulator-runner@v2.14.3


